# Input directory

input: # must contain .fa files
    fasta_dir: "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/metawrap_bins"
    stats_csv: "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/drep/mags_checkm.csv"

# output directory

output: # directory to store results
    "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/magscreen_wf"

# required database

databases:
    mash: "/hps/nobackup2/production/metagenomics/databases/human-gut_resource/mash_databases/uhgg_v1.1.msh"
    gunc: "/nfs/production/interpro/metagenomics/mags-scripts/gunc_db/gunc_db_2.0.4.dmnd"
