# input directory

input: # must contain .fa files
    fasta_dir: "/rds/project/rds-aFEMMKDjWlo/rarora/mags/genomes"
    stats_csv: "/rds/project/rds-aFEMMKDjWlo/rarora/mags/checkm.csv"

# output directory

output: # directory to store results
    "/rds/project/rds-aFEMMKDjWlo/rarora/mags/magscreen"

# required database

databases:
    mash: "/rds/project/rds-aFEMMKDjWlo/rfs_data/databases/mash/uhgg_v1.0_all.msh"
    gunc: "/rds/project/rds-aFEMMKDjWlo/rfs_data/databases/gunc/gunc_db_progenomes2.1.dmnd"
