# input directory

input: # must contain .fa files
    fasta_dir: "/rds/user/aa2369/hpc-work/scripts/snakemake/magscreen/test/input"
    stats_csv: "/rds/user/aa2369/hpc-work/scripts/snakemake/magscreen/test/input/checkm.csv"

# output directory

output: # directory to store results
    "/rds/user/aa2369/hpc-work/scripts/snakemake/magscreen/test/output"

# required database

databases:
    mash: "/rfs/project/rfs-42V0sRc5Rk8/databases/mash/uhgg_v1.0_all.msh"
    gunc: "/rfs/project/rfs-42V0sRc5Rk8/databases/gunc/gunc_db_progenomes2.1.dmnd"
